#!/bin/bash

echo
echo "--- Metrics: Making process-overhead-test --- "

pushd ~/utils/metrics/overhead
make process-overhead-test
popd

ln -s ~/utils/metrics/overhead/process-overhead-test ~/bin/

echo
echo "--- Metrics: Making gpio tests --- "

pushd ~/utils/metrics/gpio
gcc -o gpio-toggle-test gpio-toggle-test.c -lwiringPi
make uart-printf-test
popd

ln -s ~/utils/metrics/gpio/gpio-toggle-test ~/bin/
ln -s ~/utils/metrics/gpio/uart-printf-test ~/bin/

